# Change these first
owner: doquocvinh
repo: UptimeMonitoring

sites:
  - name: TUMI Japan
    url: https://www.tumi.co.jp
  - name: TUMI Korea
    url: https://www.tumi.co.kr
  - name: TUMI Singapore
    url: https://www.tumi.sg
  - name: TUMI Malaysia
    url: https://www.tumi.my
  - name: TUMI Australia
    url: https://www.tumi.com.au
  - name: TUMI Thailand
    url: https://www.tumi.co.th/th/home
  - name: TUMI Indonesia
    url: https://www.tumi.co.id/id/home
  - name: TUMI HongKong
    url: https://www.tumi-hk.com/en/home
  - name: aawq016 test
    url: https://aawq-016.dx.commercecloud.salesforce.com/s/Tumi_MY/home

assignees:
  - globeefred1989
  - jamespham1705
  - doquocvinh273

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  baseUrl: /UptimeMonitoring