# Change these first
owner: doquocvinh273
repo: UptimeMonitoring

sites:
  - name: Tumi Test
    url: https://aawq-016.dx.commercecloud.salesforce.com/s/Tumi_MY/home

assignees:
  - doquocvinh273

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  baseUrl: /UptimeMonitoring
  name: Uptime Status

skipDeleteIssues: true